### ISSUE TITLE
syntax error near unexpected token `('

### ISSUE THREAD

**Issue by laiyousin** [ICD20/hw2#12]
助教您好~想請問為何會造成此錯誤？？
![syntax error](https://user-images.githubusercontent.com/68462169/97544457-9b24be80-1a04-11eb-957c-32c282ced184.PNG)
以下是在parser中prog的寫法
![prog寫法](https://user-images.githubusercontent.com/68462169/97544877-2c943080-1a05-11eb-8ec1-279882ee4795.PNG)
謝謝助教!!

**Comment by nobodyzxc** [comment]
你直接把 p 語言當作 shell script 執行了，
你想要做的事情應該是 `./parser test/test00*.p`。

**Comment by laiyousin** [comment]
了解!!謝謝助教~~
