### ISSUE TITLE
unmatched token：(

### ISSUE THREAD

**Issue by laiyousin** [ICD20/hw2#14]
助教您好
由於執行test時遇到(就無法match，將原本scanner的資訊印出後應該有成功scan到該token，一直找不到無法match的原因
![(](https://user-images.githubusercontent.com/68462169/97670623-98d46a00-1ac1-11eb-88ec-f35e3911f75c.PNG)
下圖為prog的寫法
![prog寫法](https://user-images.githubusercontent.com/68462169/97670628-9a9e2d80-1ac1-11eb-8a8a-a110062a8fec.PNG)
麻煩助教了~~

**Comment by nobodyzxc** [comment]
你的 scanner 裡面，自己定義的 rule 沒有 return token，請參考上面的 keyword rule。

**Comment by laiyousin** [comment]
先前的問題已解決，但仍過不了測資，以test00-runtime-range-check/0.mod.token.src為例，用diff比對和answer是相同的，想知道問題在哪？？
![diff1](https://user-images.githubusercontent.com/68462169/97676175-308a8600-1acb-11eb-92aa-e4600a0e7c99.PNG)
![diff](https://user-images.githubusercontent.com/68462169/97676177-31bbb300-1acb-11eb-90df-3789d01814b2.PNG)
![錯誤](https://user-images.githubusercontent.com/68462169/97676178-32544980-1acb-11eb-82a5-178351415956.PNG)
麻煩助教了~非常感謝!!!

**Comment by nobodyzxc** [comment]
你好，這個 script 放成舊版了，沒有考慮到 moba 的 diff 版本，需要更新一下。

更新後的版本：https://github.com/ICD20/hw2/blob/main/test/test.sh

**Comment by laiyousin** [comment]
謝謝助教!!!
