### ISSUE TITLE
關於test-mini-nested-subprogram.p的問題

### ISSUE THREAD

**Issue by sugaarrrr** [ICD20/hw2#8]
助教好,

麻煩問助教一下關於這一題的問題. 當我執行test-mini-nested-subprogram.p時有出現了這個error
![image](https://user-images.githubusercontent.com/55147734/97397479-490c6c00-1924-11eb-842a-e839353b61ac.png)
這個可能是因為那個spec的grammar錯誤嗎? 還是我們需要在grammar中再加一些rule來解決這個問題?
謝謝您!

**Comment by nobodyzxc** [comment]
我猜可能是你 declarations 沒有給 lambda，
grammar 是沒有問題的，
你可以在 yacc 的 token 之間用 `{ printf(...); }` 去 debug。

**Comment by sugaarrrr** [comment]
抱歉抱歉, 不是lambda的錯誤, 才發現是我自己的錯誤 . 感謝助教!
